# Generated by Django 3.1.2 on 2020-10-31 09:29

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssetCode', models.CharField(max_length=100, verbose_name='کد تجهیز')),
                ('AssetName', models.CharField(max_length=200, verbose_name='نام تجهیز')),
                ('InstallationDate', django_jalali.db.models.jDateField(verbose_name='تاریخ نصب')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
            ],
            options={
                'verbose_name': 'تجهیز',
                'verbose_name_plural': 'تجهیزات',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssetCategoryCode', models.CharField(max_length=100, verbose_name='کد خانواده تجهیز')),
                ('AssetCategoryName', models.CharField(max_length=100, verbose_name='نام خانواده تجهیز')),
                ('slug', models.SlugField(max_length=100)),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('AssetClassFather', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.assetcategory', verbose_name='خانواده تجهیز پدر')),
            ],
            options={
                'verbose_name': 'خانواده تجهیز',
                'verbose_name_plural': 'خانواده های تجهیز',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssetClassCode', models.CharField(max_length=100, verbose_name='کد کلاس تجهیز')),
                ('AssetClassName', models.CharField(max_length=200, verbose_name='نام کلاس تجیز')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('AssetCategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.assetcategory', verbose_name='خانواده تجیز')),
            ],
            options={
                'verbose_name': 'کلاس تجهیز',
                'verbose_name_plural': 'کلاس های تجهیز',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='AssetClassTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskCode', models.CharField(max_length=100, verbose_name='کد وظیفه')),
                ('TaskName', models.CharField(max_length=200, verbose_name='نام وظیفه')),
                ('TaskDescription', models.TextField(verbose_name='توضیحات')),
                ('FrequencyName', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly'), ('F', 'Functionally')], max_length=1, verbose_name='نام تناوب')),
                ('FrequencyAmount', models.IntegerField(verbose_name='مقدار تناوب')),
                ('DurationOfDo', models.IntegerField(verbose_name='مدت زمان انجام')),
                ('Functor', models.CharField(choices=[('O', 'Operator'), ('T', 'Technician')], max_length=1, verbose_name='مسئول')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
            ],
            options={
                'verbose_name': 'وظیفه',
                'verbose_name_plural': 'وظایف',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='AssetPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssetPriorityCode', models.CharField(max_length=100, verbose_name='کد اولویت')),
                ('AssetPriorityName', models.CharField(max_length=200, verbose_name='نام اولویت')),
                ('AssetPriorityValue', models.IntegerField(verbose_name='ارزش اولویت')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
            ],
            options={
                'verbose_name': 'اولویت',
                'verbose_name_plural': 'اولویت ها',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='AssetSubdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('AssetChildID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.assetclass', verbose_name='زیر تجهیز')),
                ('AssetID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.asset', verbose_name='تجهیز')),
                ('AssetSubdivisionFatherID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.assetsubdivision', verbose_name='کلاس پدر')),
            ],
            options={
                'verbose_name': 'زیر مجموعه',
                'verbose_name_plural': 'زیر مجموعه',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='Delay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DelayCode', models.CharField(max_length=100, verbose_name='کد تاخیر')),
                ('DelayName', models.CharField(max_length=200, verbose_name='نام تاخیر')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
            ],
            options={
                'verbose_name': 'تاخیر',
                'verbose_name_plural': 'تاخیر ها',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartmentCode', models.CharField(max_length=100, verbose_name='کد دپارتمان')),
                ('DepartmentName', models.CharField(max_length=200, verbose_name='نام دپارتمان')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
            ],
            options={
                'verbose_name': 'دپارتمان',
                'verbose_name_plural': 'دپارتمان ها',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocumentCode', models.CharField(max_length=100, verbose_name='کد فایل')),
                ('DocumentName', models.CharField(max_length=200, verbose_name='نام فایل')),
                ('DocumentDescription', models.TextField(verbose_name='توضیحات')),
                ('FileAddress', models.FileField(upload_to='', verbose_name='فایل')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
            ],
            options={
                'verbose_name': 'قایل',
                'verbose_name_plural': 'فایل ها',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='FailureCause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FailureCauseCode', models.CharField(max_length=100, verbose_name='کد علت خرابی')),
                ('FailureCauseName', models.CharField(max_length=200, verbose_name='نام علت حرابی')),
                ('FailureCauseDescription', models.TextField(verbose_name='توضیحات')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
            ],
            options={
                'verbose_name': 'علت خرابی',
                'verbose_name_plural': 'علل خرابی',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='FailureMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FailureModeCode', models.CharField(max_length=100, verbose_name='کد نوع خرابی')),
                ('FailureModeName', models.CharField(max_length=200, verbose_name='نام نوع حرابی')),
                ('FailureModeDescription', models.TextField(verbose_name='توضیحات')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('AssetClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.assetclass', verbose_name='کلاس تجهیز')),
            ],
            options={
                'verbose_name': 'نوع خرابی',
                'verbose_name_plural': 'انواع خرابی',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FrequencyCode', models.CharField(max_length=100, verbose_name='کد تناوب')),
                ('FrequencyName', models.CharField(max_length=200, verbose_name='نام تناوب')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
            ],
            options={
                'verbose_name': 'تناوب',
                'verbose_name_plural': 'تناوب ها',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobCategoryCode', models.CharField(max_length=100, verbose_name='کد نوع شغل')),
                ('JobCategoryName', models.CharField(max_length=200, verbose_name='نام نوع شغل')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
            ],
            options={
                'verbose_name': 'نوع شغل',
                'verbose_name_plural': 'انواع شغل',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PersonnelCode', models.CharField(max_length=100, verbose_name='کد پرسنل')),
                ('PersonnelNetCode', models.CharField(max_length=100, verbose_name='کد نت پرسنل')),
                ('PersonnelName', models.CharField(max_length=200, verbose_name='نام پرسنل')),
                ('PersonnelFamily', models.CharField(max_length=200, verbose_name='فامیل پرسنل')),
                ('PersonnelMobile', models.CharField(max_length=100, verbose_name='شماره پرسنل')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('DepartmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.department', verbose_name='دپارتمان')),
                ('JobCategoryID', models.ManyToManyField(to='PMWorks_II.JobCategory', verbose_name='نوع شغل')),
            ],
            options={
                'verbose_name': 'پرسنل',
                'verbose_name_plural': 'پرسنل',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SparePartCode', models.CharField(max_length=100, verbose_name='کد قطعه')),
                ('SparePartName', models.CharField(max_length=200, verbose_name='نام قطعه')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
            ],
            options={
                'verbose_name': 'قطعه',
                'verbose_name_plural': 'قطعات',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='SparePartDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SparePartDimensionCode', models.CharField(max_length=100, verbose_name='کد بعد')),
                ('SparePartDimensionName', models.CharField(max_length=200, verbose_name='نام بعد')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
            ],
            options={
                'verbose_name': 'بعد قطعه',
                'verbose_name_plural': 'بعد قطعات',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='SpecificData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpecificDataCode', models.CharField(max_length=100, verbose_name='کد ویژگی')),
                ('SpecificDataName', models.CharField(max_length=200, verbose_name='نام ویژگی')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی ها',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SupplierCode', models.CharField(max_length=100, verbose_name='کد تامین کننده')),
                ('SupplierName', models.CharField(max_length=200, verbose_name='نام تامین کننده')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
            ],
            options={
                'verbose_name': 'تامین کننده',
                'verbose_name_plural': 'تامین کنندگان',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='SupplierSpecific',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SupplierSpecificCode', models.CharField(max_length=100, verbose_name='کد ویژگی تامین کننده')),
                ('SupplierSpecificName', models.CharField(max_length=200, verbose_name='نام ویژگی تامین کننده')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
            ],
            options={
                'verbose_name': 'ویژگی تامین کننده',
                'verbose_name_plural': 'ویژگی های تامین کننده',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskTypeCode', models.CharField(max_length=100, verbose_name='کد نوع وظیفه')),
                ('TaskTypeName', models.CharField(max_length=200, verbose_name='نام نوع وظیفه')),
                ('TaskTypeDescription', models.TextField(blank=True, verbose_name='توضیحات')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
            ],
            options={
                'verbose_name': 'نوع وظیفه',
                'verbose_name_plural': 'انواع وظیفه',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='TypeWr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeWrCode', models.CharField(max_length=100, verbose_name='کد نوع درخواست کار')),
                ('TypeWrName', models.CharField(max_length=200, verbose_name='نام نوع درخواست کار')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
            ],
            options={
                'verbose_name': 'نوع درخواست کار',
                'verbose_name_plural': 'انواع درخواست کار',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WODateOfRegistration', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('WODescription', models.TextField(verbose_name='توضیحات')),
                ('DateOfPlanStart', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع')),
                ('DateOfPlanFinish', django_jalali.db.models.jDateField(verbose_name='تاریخ پایان')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
            ],
            options={
                'verbose_name': 'دستور کار',
                'verbose_name_plural': 'دستور کار ها',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='WorkPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkPriorityCode', models.CharField(max_length=100, verbose_name='کد اولویت')),
                ('WorkPriorityName', models.CharField(max_length=200, verbose_name='نام اولویت')),
                ('WorkPriorityValue', models.IntegerField(verbose_name='مقدار اولویت')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
            ],
            options={
                'verbose_name': 'اولویت درخواست کار',
                'verbose_name_plural': 'اولویت های درخواست کار',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='WOTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WOTemplateCode', models.CharField(max_length=100, verbose_name='کد تناوب دستور کار')),
                ('WOTemplateName', models.CharField(max_length=200, verbose_name='نام تناوب دستور کار')),
                ('WOTemplateDurationDay', models.IntegerField(verbose_name='روز تناوب')),
                ('WOTemplateDurationHour', models.IntegerField(verbose_name='ساعت تناوب')),
                ('WOTemplateAlarmDay', models.IntegerField(verbose_name='روز اعلام تناوب')),
                ('WOTemplateAlarmHour', models.IntegerField(verbose_name='ساعت اعلام تناوب')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('AssetClassTaskID', models.ManyToManyField(to='PMWorks_II.AssetClassTask', verbose_name='وظایف')),
                ('DepartmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.department', verbose_name='دپارتمان')),
            ],
            options={
                'verbose_name': 'تناوب دستور کار',
                'verbose_name_plural': 'تناوب های دستور کار',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='WOTemplateSchualing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WOTemplateSchualingStartDate', django_jalali.db.models.jDateField(verbose_name='روز شروع برنامه')),
                ('WOTemplateSchualingFinishDate', django_jalali.db.models.jDateField(verbose_name='روز پایان برنامه')),
                ('AmountFrequency', models.IntegerField(verbose_name='مقدار')),
                ('Status', models.BooleanField(verbose_name='وضعیت')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('FrequencyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.frequency', verbose_name='تناوب')),
                ('WOTemplateID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.wotemplate', verbose_name='دستور کار')),
            ],
            options={
                'verbose_name': 'برنامه ریزی شده',
                'verbose_name_plural': 'برنامه ریزی شده ها',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='WOTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WOTaskSituationOfDo', models.CharField(max_length=50, verbose_name='وضعیت انجام')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('TaskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.assetclasstask', verbose_name='وظیفه')),
                ('WorkOrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.workorder', verbose_name='دستور کار')),
            ],
            options={
                'verbose_name': 'وظیفه دستور کار',
                'verbose_name_plural': 'وظایف دستور کار',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='WOSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkStartDate', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع')),
                ('WorkFinishDate', django_jalali.db.models.jDateField(verbose_name='تاریخ پایان')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('SupplierID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.supplier', verbose_name='تامین کنده')),
                ('WorkOrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.workorder', verbose_name='دستور کار')),
            ],
            options={
                'verbose_name': 'تامین کننده دستور کار',
                'verbose_name_plural': 'تامین کننده های دستور کار',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='WOSparePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SparePartAmount', models.IntegerField(verbose_name='تعداد قطعه')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('SparePartID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.sparepart', verbose_name='قطعه')),
                ('WorkOrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.workorder', verbose_name='دستور کار')),
            ],
            options={
                'verbose_name': 'قطعه دستور کار',
                'verbose_name_plural': 'قطعات دستور کار',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WRDate', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('WRDateOfRegistration', django_jalali.db.models.jDateField(verbose_name='تاریخ ثبت')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('AssetSubdivisionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.assetsubdivision', verbose_name='تجهیز')),
                ('FailureCauseID', models.ManyToManyField(to='PMWorks_II.FailureCause', verbose_name='علل خرابی')),
                ('FailureModeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.failuremode', verbose_name='نوع خرابی')),
                ('TypeWrID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.typewr', verbose_name='نوع')),
                ('WorkPriorityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.workpriority', verbose_name='اولویت')),
            ],
            options={
                'verbose_name': 'درخواست کار',
                'verbose_name_plural': 'درخواست کار ها',
                'ordering': ['-Create'],
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='WorkRequestID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.workrequest', verbose_name='درخواست کار'),
        ),
        migrations.CreateModel(
            name='WOPersonnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkDate', django_jalali.db.models.jDateField(verbose_name='تاریخ انجام')),
                ('WorkTime', models.IntegerField(verbose_name='مدت زمان انجام')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('PersonnelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.personnel', verbose_name='پرسنل')),
                ('WorkOrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.workorder', verbose_name='دستور کار')),
            ],
            options={
                'verbose_name': 'پرسنل دستور کار',
                'verbose_name_plural': 'پرسنل های دستور کار',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='WODelay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DayAmount', models.IntegerField(verbose_name='روز')),
                ('HourAmount', models.IntegerField(verbose_name='ساعت')),
                ('WODelayDescription', models.TextField(verbose_name='توضیحات')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('DelayID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.delay', verbose_name='تاخیر')),
                ('WorkOrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.workorder', verbose_name='دستور کار')),
            ],
            options={
                'verbose_name': 'تاخیر دستور کار',
                'verbose_name_plural': 'تاخیر های دستور کار',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='SupplierSpecificData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpecificAmount', models.CharField(max_length=50, verbose_name='مقدار ویژگی')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('SupplierID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.supplier', verbose_name='تامین کننده')),
                ('SupplierSpecificID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.supplierspecific', verbose_name='ویژگی')),
            ],
            options={
                'verbose_name': 'ویژگی های تامین کننده',
                'verbose_name_plural': 'ویژگی های تامین کنندگان',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='SparePartCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SparePartCategoryCode', models.CharField(max_length=100, verbose_name='کد خانواده قطعه')),
                ('SparePartCategoryName', models.CharField(max_length=200, verbose_name='نام خانواده قطعه')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('SparePartCategoryFather', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.sparepartcategory', verbose_name='خانواده قطعه  پدر')),
            ],
            options={
                'verbose_name': 'خانواده قطعه',
                'verbose_name_plural': 'خانواده های قطعه',
                'ordering': ['-Create'],
            },
        ),
        migrations.AddField(
            model_name='sparepart',
            name='SparePartCategoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.sparepartcategory', verbose_name='خانواده قطعه'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='SparePartDimensionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.sparepartdimension', verbose_name='بعد قطعه'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationCode', models.CharField(max_length=100, verbose_name='کد مکان')),
                ('LocationName', models.CharField(max_length=200, verbose_name='نام مکان')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('LocationFatherID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.location', verbose_name='مکان پدر')),
            ],
            options={
                'verbose_name': 'مکان',
                'verbose_name_plural': 'مکان ها',
                'ordering': ['-Create'],
            },
        ),
        migrations.AddField(
            model_name='failurecause',
            name='FailureModeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.failuremode', verbose_name='نوع خرابی'),
        ),
        migrations.AddField(
            model_name='assetsubdivision',
            name='SparePartID',
            field=models.ManyToManyField(blank=True, to='PMWorks_II.SparePart', verbose_name='قطعات یدکی'),
        ),
        migrations.CreateModel(
            name='AssetSpecificData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpecificAmount', models.IntegerField(blank=True, verbose_name='مقدار ویژگی')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('AssetSubdivisionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.assetsubdivision', verbose_name='تجهیز')),
                ('SpecificDataID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.specificdata', verbose_name='ویژگی')),
            ],
            options={
                'verbose_name': 'ویژگی تجهیز',
                'verbose_name_plural': 'ویژگی تجهیزات',
                'ordering': ['-Create'],
            },
        ),
        migrations.AddField(
            model_name='assetclasstask',
            name='AssetSubdivisionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.assetsubdivision', verbose_name='زیر تجهیز'),
        ),
        migrations.AddField(
            model_name='assetclasstask',
            name='JobCategoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.jobcategory', verbose_name='نوع شغل'),
        ),
        migrations.AddField(
            model_name='assetclasstask',
            name='TaskTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.tasktype', verbose_name='نوع وظیفه'),
        ),
        migrations.CreateModel(
            name='AssetClassSubdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssetClassChildNumber', models.IntegerField(verbose_name='تعداد فرزند')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('AssetClassChildID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClassChild', to='PMWorks_II.assetclass', verbose_name='کلاس تجیز فرزند')),
                ('AssetClassFatherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClassFather', to='PMWorks_II.assetclass', verbose_name='کلاس تجهیز پدر')),
            ],
            options={
                'verbose_name': 'زیر کلاس تجهیز',
                'verbose_name_plural': 'زیر کلاس تجهیزات',
                'ordering': ['-Create'],
            },
        ),
        migrations.AddField(
            model_name='assetclass',
            name='SpecificDataID',
            field=models.ManyToManyField(to='PMWorks_II.SpecificData', verbose_name='وِیژگی ها'),
        ),
        migrations.AddField(
            model_name='asset',
            name='AssetClassID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.assetclass', verbose_name='کلاس تجهیز'),
        ),
        migrations.AddField(
            model_name='asset',
            name='AssetPriorityID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.assetpriority', verbose_name='اولویت'),
        ),
        migrations.AddField(
            model_name='asset',
            name='DocumentID',
            field=models.ManyToManyField(blank=True, to='PMWorks_II.Document', verbose_name='فایل ها'),
        ),
        migrations.AddField(
            model_name='asset',
            name='LocationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.location', verbose_name='مکان'),
        ),
    ]
