# Generated by Django 3.1.2 on 2020-10-31 10:17

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetclass',
            name='SpecificDataID',
        ),
        migrations.CreateModel(
            name='AssetClassSpecificData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('AssetClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.assetclass', verbose_name='کلاس تجهیز')),
                ('SpecificDataID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.specificdata', verbose_name='ویژگی')),
            ],
            options={
                'verbose_name': 'زیر کلاس تجهیز',
                'verbose_name_plural': 'زیر کلاس تجهیزات',
                'ordering': ['-Create'],
            },
        ),
    ]
