# Generated by Django 3.1.2 on 2020-11-07 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0002_auto_20201031_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetclassspecificdata',
            options={'ordering': ['-Create'], 'verbose_name': 'مشخصات کلاس', 'verbose_name_plural': 'مشخصات کلاس ها'},
        ),
        migrations.AlterField(
            model_name='assetclassspecificdata',
            name='AssetClassID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.assetclass', verbose_name='کلاس تجهیز'),
        ),
    ]
