# Generated by Django 3.1.2 on 2020-11-17 07:08

import PMWorks_II.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0003_auto_20201107_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='FileAddress',
            field=models.FileField(upload_to=PMWorks_II.models.upload_path, verbose_name='فایل'),
        ),
    ]
