# Generated by Django 3.1.2 on 2020-12-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0007_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='status',
        ),
    ]
