# Generated by Django 3.1.2 on 2020-12-10 06:02

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0008_delete_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetsubdivision',
            name='SparePartID',
        ),
        migrations.AddField(
            model_name='assetsubdivision',
            name='tree',
            field=models.IntegerField(blank=True, default=1, verbose_name='وضعیت درخت'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AssetSubdivisionSparePatt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('AssetSubdivisionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.assetsubdivision', verbose_name='تجهیز')),
                ('SparePartID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.sparepart', verbose_name='قطعات یدکی')),
            ],
            options={
                'verbose_name': 'ویژگی زیر مجموعه',
                'verbose_name_plural': 'ویژگی های زیر مجموعه',
                'ordering': ['-Create'],
            },
        ),
    ]
