# Generated by Django 3.1.2 on 2020-12-17 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0009_auto_20201210_0932'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetSubdivisionSparePatt',
            new_name='AssetSubdivisionSparePart',
        ),
    ]
