# Generated by Django 3.1.2 on 2020-12-20 09:37

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0010_auto_20201217_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='JobCategoryID',
        ),
        migrations.CreateModel(
            name='PersonnelJobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('JobCategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.jobcategory', verbose_name='نوع شغل')),
                ('PersonnelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.personnel', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'شغل پرسنل',
                'verbose_name_plural': 'شغل های پرسنل',
                'ordering': ['-Create'],
            },
        ),
    ]
