# Generated by Django 3.1.2 on 2020-12-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0011_auto_20201220_1307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetDocument',
            new_name='AssetClassDocument',
        ),
        migrations.RemoveField(
            model_name='assetclassdocument',
            name='AssetID',
        ),
        migrations.AddField(
            model_name='assetclassdocument',
            name='AssetClassID',
            field=models.ForeignKey(default=3, on_delete=models.Model, to='PMWorks_II.assetclass', verbose_name='تجهیز'),
            preserve_default=False,
        ),
    ]
