# Generated by Django 3.1.2 on 2020-12-27 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0012_auto_20201227_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetclasstask',
            name='AssetSubdivisionID',
        ),
        migrations.AddField(
            model_name='assetclasstask',
            name='AssetClassID',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.assetclass', verbose_name='کلاس تجهیز'),
            preserve_default=False,
        ),
    ]
