# Generated by Django 3.1.2 on 2020-12-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0013_auto_20201227_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wopersonnel',
            name='WorkDate',
            field=models.DateField(verbose_name='تاریخ انجام'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='DateOfPlanFinish',
            field=models.DateField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='DateOfPlanStart',
            field=models.DateField(verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='WODateOfRegistration',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='WRDate',
            field=models.DateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='WRDateOfRegistration',
            field=models.DateField(verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='wosupplier',
            name='WorkFinishDate',
            field=models.DateField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='wosupplier',
            name='WorkStartDate',
            field=models.DateField(verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='wotemplateschualing',
            name='WOTemplateSchualingFinishDate',
            field=models.DateField(verbose_name='روز پایان برنامه'),
        ),
        migrations.AlterField(
            model_name='wotemplateschualing',
            name='WOTemplateSchualingStartDate',
            field=models.DateField(verbose_name='روز شروع برنامه'),
        ),
    ]
