# Generated by Django 3.1.2 on 2021-02-02 07:03

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0014_auto_20201228_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='WOTemplateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WOTemplateTypeCode', models.CharField(max_length=100, verbose_name='کد نوع برنامه')),
                ('WOTemplateTypeName', models.CharField(max_length=200, verbose_name='نام نوع برنامه')),
                ('WOTemplateTypeDescription', models.TextField(blank=True, verbose_name='توضیحات')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
            ],
            options={
                'verbose_name': 'نوع برنامه',
                'verbose_name_plural': 'انواع برنامه',
                'ordering': ['-Create'],
            },
        ),
        migrations.RemoveField(
            model_name='wotemplate',
            name='AssetClassTaskID',
        ),
        migrations.CreateModel(
            name='WOActivityTemplateTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('AssetClassTaskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.assetclasstask', verbose_name='فعالیت')),
                ('WOTemplateID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.wotemplate', verbose_name='برنامه')),
            ],
            options={
                'verbose_name': 'فعالیت های برنامه',
                'verbose_name_plural': 'فعالیت های برنامه ها',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='TemplateSchualingDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TemplateSchualingDate', models.DateField(verbose_name='روز برنامه')),
                ('StatusOfDo', models.CharField(max_length=100, verbose_name='وضعیت انجام')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('WOTemplateSchualingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.wotemplateschualing', verbose_name='برنامه')),
            ],
            options={
                'verbose_name': 'برنامه ریزی ',
                'verbose_name_plural': 'برنامه ریزی ها',
                'ordering': ['-Create'],
            },
        ),
        migrations.AddField(
            model_name='wotemplate',
            name='WOTemplateTypeID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.wotemplatetype', verbose_name='نوع'),
            preserve_default=False,
        ),
    ]
