# Generated by Django 3.1.2 on 2021-04-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0017_auto_20210430_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='fakesub',
            field=models.IntegerField(blank=True, default=1, verbose_name='زيرمجموعه فيک'),
            preserve_default=False,
        ),
    ]
