# Generated by Django 3.1.2 on 2021-05-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0019_remove_workrequest_failurecauseid'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetsubdivision',
            name='AssetClassCodeChain',
            field=models.CharField(default=1, max_length=500, verbose_name='رشته کد کلاس'),
            preserve_default=False,
        ),
    ]
