# Generated by Django 3.1.2 on 2021-05-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0021_auto_20210523_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetsubdivision',
            name='AssetCode',
            field=models.CharField(default=1, max_length=500, verbose_name='کد تجهيز'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetsubdivision',
            name='AssetName',
            field=models.CharField(default=1, max_length=500, verbose_name='نام تجهيز'),
            preserve_default=False,
        ),
    ]
