# Generated by Django 3.1.2 on 2021-06-11 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0023_workrequestfailurecause'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wotemplate',
            name='WOTemplateAlarmHour',
        ),
        migrations.RemoveField(
            model_name='wotemplate',
            name='WOTemplateDurationHour',
        ),
    ]
