# Generated by Django 3.1.2 on 2021-06-11 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0024_auto_20210611_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='wotemplate',
            name='WOTemplateDurationHour',
            field=models.IntegerField(verbose_name='ساعت تناوب'),
            preserve_default=False,
        ),
    ]
