# Generated by Django 3.1.2 on 2021-06-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0026_wotemplate_wotemplatealarmhour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wotemplateschualing',
            name='Status',
            field=models.BooleanField(default=False, verbose_name='وضعیت'),
        ),
    ]
