# Generated by Django 3.1.2 on 2021-06-27 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0027_auto_20210624_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateschualingdate',
            name='StatusOfDo',
        ),
    ]
