# Generated by Django 3.1.2 on 2021-06-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0028_remove_templateschualingdate_statusofdo'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateschualingdate',
            name='StatusOfDo',
            field=models.BooleanField(default=False, verbose_name='وضعیت انجام'),
        ),
    ]
