# Generated by Django 3.1.2 on 2021-06-30 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0029_templateschualingdate_statusofdo'),
    ]

    operations = [
        migrations.AddField(
            model_name='woactivitytemplatetbl',
            name='AssetSubdivisionID',
            field=models.ForeignKey(default=280, on_delete=django.db.models.deletion.CASCADE, to='PMWorks_II.assetsubdivision', verbose_name='تجهیز'),
            preserve_default=False,
        ),
    ]
