# Generated by Django 3.1.2 on 2021-07-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0030_woactivitytemplatetbl_assetsubdivisionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcategory',
            name='AssetCategoryCode',
            field=models.CharField(max_length=100, unique=True, verbose_name='کد خانواده تجهیز'),
        ),
        migrations.AlterField(
            model_name='assetclass',
            name='AssetClassCode',
            field=models.CharField(max_length=100, unique=True, verbose_name='کد کلاس تجهیز'),
        ),
    ]
