# Generated by Django 3.1.2 on 2021-07-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0032_auto_20210719_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificdata',
            name='Measurment',
            field=models.CharField(default=1, max_length=200, verbose_name='اندازه گيري'),
            preserve_default=False,
        ),
    ]
