# Generated by Django 3.1.2 on 2021-07-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0033_specificdata_measurment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificdata',
            name='SpecificDataCode',
            field=models.CharField(max_length=100, unique=True, verbose_name='کد ویژگی'),
        ),
    ]
