# Generated by Django 3.1.2 on 2021-08-12 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0034_auto_20210719_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcategory',
            name='AssetClassFather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.assetcategory', verbose_name='خانواده تجهیز پدر'),
        ),
    ]
