# Generated by Django 3.1.2 on 2021-08-12 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PMWorks_II', '0035_auto_20210812_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='AssetClassID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.assetclass', verbose_name='کلاس تجهیز'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='AssetPriorityID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.assetpriority', verbose_name='اولویت'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='LocationID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.location', verbose_name='مکان'),
        ),
        migrations.AlterField(
            model_name='assetclass',
            name='AssetCategoryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.assetcategory', verbose_name='خانواده تجیز'),
        ),
        migrations.AlterField(
            model_name='assetclassdocument',
            name='AssetClassID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.assetclass', verbose_name='تجهیز'),
        ),
        migrations.AlterField(
            model_name='assetclassdocument',
            name='DocumentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.document', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='assetclassspecificdata',
            name='AssetClassID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.assetclass', verbose_name='کلاس تجهیز'),
        ),
        migrations.AlterField(
            model_name='assetclassspecificdata',
            name='SpecificDataID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.specificdata', verbose_name='ویژگی'),
        ),
        migrations.AlterField(
            model_name='assetclasssubdivision',
            name='AssetClassChildID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ClassChild', to='PMWorks_II.assetclass', verbose_name='کلاس تجیز فرزند'),
        ),
        migrations.AlterField(
            model_name='assetclasssubdivision',
            name='AssetClassFatherID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ClassFather', to='PMWorks_II.assetclass', verbose_name='کلاس تجهیز پدر'),
        ),
        migrations.AlterField(
            model_name='assetclasstask',
            name='AssetClassID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.assetclass', verbose_name='کلاس تجهیز'),
        ),
        migrations.AlterField(
            model_name='assetclasstask',
            name='JobCategoryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.jobcategory', verbose_name='نوع شغل'),
        ),
        migrations.AlterField(
            model_name='assetclasstask',
            name='TaskTypeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.tasktype', verbose_name='نوع وظیفه'),
        ),
        migrations.AlterField(
            model_name='assetspecificdata',
            name='AssetSubdivisionID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.assetsubdivision', verbose_name='تجهیز'),
        ),
        migrations.AlterField(
            model_name='assetspecificdata',
            name='SpecificDataID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.specificdata', verbose_name='ویژگی'),
        ),
        migrations.AlterField(
            model_name='assetsubdivision',
            name='AssetChildID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.assetclass', verbose_name='زیر تجهیز'),
        ),
        migrations.AlterField(
            model_name='assetsubdivision',
            name='AssetID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.asset', verbose_name='تجهیز'),
        ),
        migrations.AlterField(
            model_name='assetsubdivision',
            name='AssetSubdivisionFatherID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.assetsubdivision', verbose_name='کلاس پدر'),
        ),
        migrations.AlterField(
            model_name='assetsubdivisionsparepart',
            name='AssetSubdivisionID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.assetsubdivision', verbose_name='تجهیز'),
        ),
        migrations.AlterField(
            model_name='assetsubdivisionsparepart',
            name='SparePartID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.sparepart', verbose_name='قطعات یدکی'),
        ),
        migrations.AlterField(
            model_name='failurecause',
            name='FailureModeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.failuremode', verbose_name='نوع خرابی'),
        ),
        migrations.AlterField(
            model_name='failuremode',
            name='AssetClassID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.assetclass', verbose_name='کلاس تجهیز'),
        ),
        migrations.AlterField(
            model_name='location',
            name='LocationFatherID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.location', verbose_name='مکان پدر'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='DepartmentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.department', verbose_name='دپارتمان'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='یوزر'),
        ),
        migrations.AlterField(
            model_name='personneljobcategory',
            name='JobCategoryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.jobcategory', verbose_name='نوع شغل'),
        ),
        migrations.AlterField(
            model_name='personneljobcategory',
            name='PersonnelID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.personnel', verbose_name='پرسنل'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='SparePartCategoryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.sparepartcategory', verbose_name='خانواده قطعه'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='SparePartDimensionID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.sparepartdimension', verbose_name='بعد قطعه'),
        ),
        migrations.AlterField(
            model_name='sparepartcategory',
            name='SparePartCategoryFather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.sparepartcategory', verbose_name='خانواده قطعه  پدر'),
        ),
        migrations.AlterField(
            model_name='supplierspecificdata',
            name='SupplierID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.supplier', verbose_name='تامین کننده'),
        ),
        migrations.AlterField(
            model_name='supplierspecificdata',
            name='SupplierSpecificID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.supplierspecific', verbose_name='ویژگی'),
        ),
        migrations.AlterField(
            model_name='templateschualingdate',
            name='WOTemplateSchualingID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.wotemplateschualing', verbose_name='برنامه'),
        ),
        migrations.AlterField(
            model_name='woactivitytemplatetbl',
            name='AssetClassTaskID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.assetclasstask', verbose_name='فعالیت'),
        ),
        migrations.AlterField(
            model_name='woactivitytemplatetbl',
            name='AssetSubdivisionID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.assetsubdivision', verbose_name='تجهیز'),
        ),
        migrations.AlterField(
            model_name='woactivitytemplatetbl',
            name='WOTemplateID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.wotemplate', verbose_name='برنامه'),
        ),
        migrations.AlterField(
            model_name='wodelay',
            name='DelayID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.delay', verbose_name='تاخیر'),
        ),
        migrations.AlterField(
            model_name='wodelay',
            name='WorkOrderID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.workorder', verbose_name='دستور کار'),
        ),
        migrations.AlterField(
            model_name='wopersonnel',
            name='PersonnelID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.personnel', verbose_name='پرسنل'),
        ),
        migrations.AlterField(
            model_name='wopersonnel',
            name='WorkOrderID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.workorder', verbose_name='دستور کار'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='WorkRequestID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.workrequest', verbose_name='درخواست کار'),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='AssetSubdivisionID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.assetsubdivision', verbose_name='تجهیز'),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='FailureModeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.failuremode', verbose_name='نوع خرابی'),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='TypeWrID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.typewr', verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='WorkPriorityID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.workpriority', verbose_name='اولویت'),
        ),
        migrations.AlterField(
            model_name='workrequestfailurecause',
            name='FailureCauseID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FailureCause', to='PMWorks_II.failurecause', verbose_name='علت خرابي'),
        ),
        migrations.AlterField(
            model_name='workrequestfailurecause',
            name='WorkRequestID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='WorkRequest', to='PMWorks_II.workrequest', verbose_name='درخواست کار'),
        ),
        migrations.AlterField(
            model_name='wosparepart',
            name='SparePartID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.sparepart', verbose_name='قطعه'),
        ),
        migrations.AlterField(
            model_name='wosparepart',
            name='WorkOrderID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.workorder', verbose_name='دستور کار'),
        ),
        migrations.AlterField(
            model_name='wosupplier',
            name='SupplierID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.supplier', verbose_name='تامین کنده'),
        ),
        migrations.AlterField(
            model_name='wosupplier',
            name='WorkOrderID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.workorder', verbose_name='دستور کار'),
        ),
        migrations.AlterField(
            model_name='wotask',
            name='TaskID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.assetclasstask', verbose_name='وظیفه'),
        ),
        migrations.AlterField(
            model_name='wotask',
            name='WorkOrderID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.workorder', verbose_name='دستور کار'),
        ),
        migrations.AlterField(
            model_name='wotemplate',
            name='DepartmentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.department', verbose_name='دپارتمان'),
        ),
        migrations.AlterField(
            model_name='wotemplate',
            name='WOTemplateTypeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.wotemplatetype', verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='wotemplateschualing',
            name='FrequencyID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.frequency', verbose_name='تناوب'),
        ),
        migrations.AlterField(
            model_name='wotemplateschualing',
            name='WOTemplateID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMWorks_II.wotemplate', verbose_name='دستور کار'),
        ),
    ]
