# Generated by Django 3.1.2 on 2021-08-21 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0036_auto_20210812_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcategory',
            name='AssetCategoryCode',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='کد خانواده تجهیز'),
        ),
    ]
