# Generated by Django 3.1.2 on 2021-08-21 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0037_auto_20210821_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='AssetCode',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='کد تجهیز'),
        ),
        migrations.AlterField(
            model_name='assetclass',
            name='AssetClassCode',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='کد کلاس تجهیز'),
        ),
        migrations.AlterField(
            model_name='assetclasstask',
            name='TaskCode',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='کد وظیفه'),
        ),
        migrations.AlterField(
            model_name='assetpriority',
            name='AssetPriorityCode',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='کد اولویت'),
        ),
        migrations.AlterField(
            model_name='document',
            name='DocumentCode',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='کد فایل'),
        ),
        migrations.AlterField(
            model_name='failurecause',
            name='FailureCauseCode',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='کد علت خرابی'),
        ),
        migrations.AlterField(
            model_name='failuremode',
            name='FailureModeCode',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='کد نوع خرابی'),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='JobCategoryCode',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='کد نوع شغل'),
        ),
        migrations.AlterField(
            model_name='location',
            name='LocationCode',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='کد مکان'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='SparePartCode',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='کد قطعه'),
        ),
        migrations.AlterField(
            model_name='sparepartcategory',
            name='SparePartCategoryCode',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='کد خانواده قطعه'),
        ),
        migrations.AlterField(
            model_name='sparepartdimension',
            name='SparePartDimensionCode',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='کد بعد'),
        ),
        migrations.AlterField(
            model_name='specificdata',
            name='SpecificDataCode',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='کد ویژگی'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='TaskTypeCode',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='کد نوع وظیفه'),
        ),
    ]
