# Generated by Django 3.1.2 on 2021-08-30 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0038_auto_20210821_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcategory',
            name='AssetClassFather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='PMWorks_II.assetcategory', verbose_name='خانواده تجهیز پدر'),
        ),
        migrations.AlterField(
            model_name='assetclass',
            name='AssetCategoryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='PMWorks_II.assetcategory', verbose_name='خانواده تجیز'),
        ),
    ]
