# Generated by Django 3.1.2 on 2021-10-03 12:47

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0040_auto_20210830_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='LocationCodeChain',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='کد مکانزنجيزه'),
        ),
        migrations.AddField(
            model_name='location',
            name='LocationNameChain',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='زنجيزه نام مکان'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='assetclass',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='assetclass',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='assetclassdocument',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='assetclassdocument',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='assetclassspecificdata',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='assetclassspecificdata',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='assetclasssubdivision',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='assetclasssubdivision',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='assetclasstask',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='assetclasstask',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='assetpriority',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='assetpriority',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='assetspecificdata',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='assetspecificdata',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='assetsubdivision',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='assetsubdivision',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='assetsubdivisionsparepart',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='assetsubdivisionsparepart',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='delay',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='delay',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='department',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='department',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='document',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='document',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='failurecause',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='failurecause',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='failuremode',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='failuremode',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='location',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='location',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='personneljobcategory',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='personneljobcategory',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='sparepartcategory',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='sparepartcategory',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='sparepartdimension',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='sparepartdimension',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='specificdata',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='specificdata',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='supplierspecific',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='supplierspecific',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='supplierspecificdata',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='supplierspecificdata',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='templateschualingdate',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='templateschualingdate',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='typewr',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='typewr',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='woactivitytemplatetbl',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='woactivitytemplatetbl',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='wodelay',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='wodelay',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='wopersonnel',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='wopersonnel',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='workpriority',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='workpriority',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='workrequestfailurecause',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='workrequestfailurecause',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='wosparepart',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='wosparepart',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='wosupplier',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='wosupplier',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='wotask',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='wotask',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='wotemplate',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='wotemplate',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='wotemplateschualing',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='wotemplateschualing',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='wotemplatetype',
            name='Create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='wotemplatetype',
            name='Update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر'),
        ),
    ]
