# Generated by Django 3.1.2 on 2021-10-18 13:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0041_auto_20211003_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wopersonnel',
            name='WorkOrderID',
        ),
        migrations.RemoveField(
            model_name='wosparepart',
            name='WorkOrderID',
        ),
        migrations.AddField(
            model_name='wopersonnel',
            name='WOTaskID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='PMWorks_II.wotask', verbose_name='دستور کار وظيفه'),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='WRTime',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='ساعت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workrequest',
            name='WRTimeOfRegistration',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='زمان ثبت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wosparepart',
            name='WOTaskID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='PMWorks_II.wotask', verbose_name='وظيفه دستورکار'),
        ),
    ]
