# Generated by Django 3.1.2 on 2021-10-26 12:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0042_auto_20211018_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusCode', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='کد وضعيت')),
                ('StatusName', models.CharField(max_length=200, verbose_name='نام وضعيت')),
                ('StatusCondition', models.CharField(max_length=200, verbose_name='شرايط')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر')),
            ],
            options={
                'verbose_name': 'وضعيت',
                'verbose_name_plural': 'انوع وضعيت',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkflowLevelName', models.CharField(max_length=200, verbose_name='نام سطح')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر')),
            ],
            options={
                'verbose_name': 'سطح وضعيت',
                'verbose_name_plural': 'سطوح وضعيت',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='WRWORelationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر')),
                ('StatusWOID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='WorkOrder', to='PMWorks_II.status', verbose_name='دستور کار')),
                ('StstusWRID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='WorkRequest', to='PMWorks_II.status', verbose_name='درخواست کار')),
            ],
            options={
                'verbose_name': 'ارتباط وضعيت',
                'verbose_name_plural': 'ارتباط وضعيت ها',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='WRStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusDate', models.DateField(verbose_name='تاریخ ثبت')),
                ('StatusTime', models.TimeField(verbose_name='زمان ثبت')),
                ('StatusDescription', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر')),
                ('StatusID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='PMWorks_II.status', verbose_name='وضعيت')),
                ('WorkRequestID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='PMWorks_II.workrequest', verbose_name='درخواست کار')),
            ],
            options={
                'verbose_name': 'وضعيت درخواست کار',
                'verbose_name_plural': 'وضعيت هاي درخواستت کار',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='WOStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusDate', models.DateField(verbose_name='تاریخ ثبت')),
                ('StatusTime', models.TimeField(verbose_name='زمان ثبت')),
                ('StatusDescription', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر')),
                ('StatusID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='PMWorks_II.status', verbose_name='وضعيت')),
                ('WorkOrderID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='PMWorks_II.workorder', verbose_name='دستور کار')),
            ],
            options={
                'verbose_name': 'وضعيت دستور کار',
                'verbose_name_plural': 'وضعيت هاي دستور کار',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowLevelStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkflowLevelStatusPeriority', models.IntegerField(blank=True, verbose_name='اولويت')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر')),
                ('StatusID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='PMWorks_II.status', verbose_name='وضعيت')),
                ('WorkflowLevelID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='PMWorks_II.workflowlevel', verbose_name='سطح')),
            ],
            options={
                'verbose_name': 'کار سطح وضعيت',
                'verbose_name_plural': 'کار سطوح وضعيت',
                'ordering': ['-Create'],
            },
        ),
    ]
