# Generated by Django 3.1.2 on 2021-10-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0044_auto_20211027_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='Status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='وضعيت'),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='Status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='وضعيت'),
        ),
    ]
