# Generated by Django 3.1.2 on 2021-10-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0045_auto_20211027_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='WODescription',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
