# Generated by Django 3.1.2 on 2021-11-10 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0046_auto_20211028_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='workrequest',
            name='Status',
        ),
        migrations.AddField(
            model_name='status',
            name='OpCl',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='وضعيت'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='StatusID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='PMWorks_II.status', verbose_name='وضعيت'),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='StatusID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='PMWorks_II.status', verbose_name='وضعيت'),
        ),
    ]
