# Generated by Django 4.0 on 2022-01-05 11:58

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0048_workorder_dateoffinish_workorder_dateofstart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowLevelStatusShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر')),
                ('StatusID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='PMWorks_II.status', verbose_name='وضعيت')),
                ('WorkflowLevelID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='PMWorks_II.workflowlevel', verbose_name='سطح')),
            ],
            options={
                'verbose_name': 'نشان کار سطح وضعيت',
                'verbose_name_plural': 'نشان کار سطوح وضعيت',
                'ordering': ['-Create'],
            },
        ),
    ]
