# Generated by Django 4.0 on 2022-01-05 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0049_workflowlevelstatusshow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowlevelstatusshow',
            name='WorkflowLevelID',
        ),
        migrations.AddField(
            model_name='workflowlevelstatusshow',
            name='WorkflowLevelStatusID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='PMWorks_II.workflowlevelstatus', verbose_name='سطح'),
        ),
    ]
