# Generated by Django 4.0 on 2022-03-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0051_alter_workorder_dateoffinish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrequest',
            name='WRDescription',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
