# Generated by Django 4.0 on 2022-03-14 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0052_workrequest_wrdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='InstallationDate',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ نصب'),
        ),
        migrations.AlterField(
            model_name='assetclasstask',
            name='DurationOfDo',
            field=models.IntegerField(blank=True, null=True, verbose_name='مدت زمان انجام'),
        ),
        migrations.AlterField(
            model_name='assetclasstask',
            name='FrequencyAmount',
            field=models.IntegerField(blank=True, null=True, verbose_name='مقدار تناوب'),
        ),
        migrations.AlterField(
            model_name='assetclasstask',
            name='FrequencyName',
            field=models.CharField(blank=True, choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly'), ('F', 'Functionally')], max_length=1, null=True, verbose_name='نام تناوب'),
        ),
        migrations.AlterField(
            model_name='assetclasstask',
            name='Functor',
            field=models.CharField(blank=True, choices=[('O', 'Operator'), ('T', 'Technician')], max_length=1, null=True, verbose_name='مسئول'),
        ),
        migrations.AlterField(
            model_name='assetclasstask',
            name='JobCategoryID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='PMWorks_II.jobcategory', verbose_name='نوع شغل'),
        ),
        migrations.AlterField(
            model_name='assetclasstask',
            name='TaskDescription',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='assetspecificdata',
            name='SpecificAmount',
            field=models.IntegerField(blank=True, null=True, verbose_name='مقدار ویژگی'),
        ),
        migrations.AlterField(
            model_name='document',
            name='DocumentDescription',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='failurecause',
            name='FailureCauseDescription',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='failuremode',
            name='FailureModeDescription',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='PersonnelMobile',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره پرسنل'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='TaskTypeDescription',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='wotemplatetype',
            name='WOTemplateTypeDescription',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
