# Generated by Django 4.0 on 2022-03-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0053_alter_asset_installationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateschualingdate',
            name='TemplateSchualingDate',
            field=models.DateTimeField(verbose_name='روز برنامه'),
        ),
    ]
