# Generated by Django 4.0 on 2022-03-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0054_alter_templateschualingdate_templateschualingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wotemplateschualing',
            name='WOTemplateSchualingFinishDate',
            field=models.DateTimeField(verbose_name='روز پایان برنامه'),
        ),
        migrations.AlterField(
            model_name='wotemplateschualing',
            name='WOTemplateSchualingStartDate',
            field=models.DateTimeField(verbose_name='روز شروع برنامه'),
        ),
    ]
