# Generated by Django 4.0 on 2022-03-23 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0055_alter_wotemplateschualing_wotemplateschualingfinishdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templateschualingdate',
            old_name='TemplateSchualingDate',
            new_name='SchualingDate',
        ),
        migrations.AddField(
            model_name='templateschualingdate',
            name='SchedualingAlarmDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='روز اعلام برنامه'),
            preserve_default=False,
        ),
    ]
