# Generated by Django 4.0 on 2022-03-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0057_alter_wotemplate_wotemplatealarmhour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wotemplate',
            name='WOTemplateAlarmHour',
        ),
    ]
