# Generated by Django 4.0 on 2022-03-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0059_wotemplate_wotemplatealarmhour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wotemplate',
            name='WOTemplateDurationHour',
        ),
    ]
