# Generated by Django 4.0 on 2022-03-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0060_remove_wotemplate_wotemplatedurationhour'),
    ]

    operations = [
        migrations.AddField(
            model_name='wotemplate',
            name='WOTemplateDurationHour',
            field=models.IntegerField(default=1, verbose_name='ساعت تناوب'),
            preserve_default=False,
        ),
    ]
