# Generated by Django 4.0 on 2022-03-25 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0061_wotemplate_wotemplatedurationhour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wotemplateschualing',
            name='FrequencyID',
        ),
        migrations.AddField(
            model_name='wotemplateschualing',
            name='FrequencyName',
            field=models.CharField(default='D', max_length=100, verbose_name='تناوب'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='templateschualingdate',
            name='WOTemplateSchualingID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='PMWorks_II.wotemplateschualing', verbose_name='برنامه'),
        ),
        migrations.AlterField(
            model_name='wotemplate',
            name='DepartmentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='PMWorks_II.department', verbose_name='دپارتمان'),
        ),
        migrations.AlterField(
            model_name='wotemplate',
            name='WOTemplateAlarmDay',
            field=models.IntegerField(blank=True, null=True, verbose_name='روز اعلام تناوب'),
        ),
        migrations.AlterField(
            model_name='wotemplate',
            name='WOTemplateAlarmHour',
            field=models.IntegerField(blank=True, null=True, verbose_name='ساعت اعلام تناوب'),
        ),
        migrations.AlterField(
            model_name='wotemplate',
            name='WOTemplateTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='PMWorks_II.wotemplatetype', verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='wotemplateschualing',
            name='WOTemplateID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='PMWorks_II.wotemplate', verbose_name='دستور کار'),
        ),
        migrations.DeleteModel(
            name='Frequency',
        ),
    ]
