# Generated by Django 4.0 on 2022-04-03 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0063_wotemplateactivity_wotemplateasset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wotemplateasset',
            name='AssetID',
        ),
        migrations.AddField(
            model_name='workorder',
            name='WorkOrderType',
            field=models.BinaryField(blank=True, null=True, verbose_name='نوع'),
        ),
        migrations.AddField(
            model_name='wotemplateasset',
            name='AssetSubdivisionID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='PMWorks_II.assetsubdivision', verbose_name='تجهیز'),
            preserve_default=False,
        ),
    ]
