# Generated by Django 4.0 on 2022-04-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0064_remove_wotemplateasset_assetid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='WorkOrderType',
            field=models.TextField(blank=True, null=True, verbose_name='نوع'),
        ),
    ]
