# Generated by Django 4.0 on 2022-04-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0065_alter_workorder_workordertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='WOTemplateCode',
            field=models.TextField(blank=True, null=True, verbose_name='کد برنامه'),
        ),
    ]
