# Generated by Django 4.0 on 2022-04-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0066_workorder_wotemplatecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowlevel',
            name='WorkflowLevelType',
            field=models.CharField(default='WR', max_length=200, verbose_name='نوع سطح'),
            preserve_default=False,
        ),
    ]
