# Generated by Django 4.0 on 2022-04-30 16:24

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PMWorks_II', '0067_workflowlevel_workflowleveltype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wotask',
            name='WorkOrderID',
        ),
        migrations.CreateModel(
            name='WOAssetSubdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر')),
                ('AssetSubdivisionID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='PMWorks_II.assetsubdivision', verbose_name='تامین کنده')),
                ('WorkOrderID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='PMWorks_II.workorder', verbose_name='دستور کار')),
            ],
            options={
                'verbose_name': 'تجهيز دستور کار',
                'verbose_name_plural': 'تجهيزات دستور کار',
                'ordering': ['-Create'],
            },
        ),
        migrations.AddField(
            model_name='wotask',
            name='WOAssetSubdivisionID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='PMWorks_II.woassetsubdivision', verbose_name='دستور کار'),
        ),
    ]
