# Generated by Django 4.0 on 2022-05-18 14:46

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('PMWorks_II', '0069_alter_personnel_personnelnetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleName', models.CharField(max_length=200, verbose_name='نام نقش')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر')),
            ],
            options={
                'verbose_name': 'نقش',
                'verbose_name_plural': 'نقش ها',
                'ordering': ['-Create'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('Update', django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین تغییر')),
                ('RoleID', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='PMWorks_II.role', verbose_name='نقش')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='auth.user', verbose_name='یوزر')),
            ],
            options={
                'verbose_name': 'نقش يوزر',
                'verbose_name_plural': 'نقش هاي يوزر',
                'ordering': ['-Create'],
            },
        ),
    ]
